### PR TITLE
Streaming interface for Websocket communications

### PR DESCRIPTION
**Pull request by ottiker**
The new communication interface should look, more or less, like this:

Creating a link:

``` js
// create link (the callback is executed, when `link.end` is called)
var link = self.link('linkName', function (err, data) {});
// receive data
link.data(function (chunk) {});
// send data
link.send(data);
// end connection
link.end(err, data);
```

Method called by a link:

``` js
function method (event) {
    var link = event.link;
    // receive data
    link.data(function (chunk) {});
    // send data
    link.send(data);
    // end connection
    link.end(err, data)
}
```

### CODE REVIEW

**Comment by ottiker** [comment]
Probably issue #131 can be fixed with this pull request.

**Comment by IonicaBizau** [comment]
What if if we need multiple listeners on the same link?

Something like this?

``` js
link.data(function (chunk) {});
link.data(function (chunk) {});
```

**Comment by ottiker** [comment]
For example, `link.send` can be called multiple times to stream down data. We could do the same with `link.data` listeners. Every time `link.data` is called, a listener is added.

``` js
// data listener 1
link.data(function (chunk) {});
// data listener 2
link.data(function (chunk) {});
```

Otherwise we have to switch to the "traditional" observer API with `on`, `removeListener`, etc.

Can you post some code from the Terminal module code, where you need live updates (push) from the server?

**Comment by IonicaBizau** [comment]
Yes, that's fine.

See the [`on` calls](https://github.com/IonicaBizau/browser-terminal/blob/tty.js/bin/public/tty.js#L73-L92).

**Comment by IonicaBizau** [comment]
This looks like an awesome and big change! :smile: :star:

**Comment by ottiker** [comment]
yes!
Beside the "real-time data models", every thing should be done, when you finished your exams.
- server-push
- (real-time data models)
- easy pluggable modules
- server-side flow configuration
- better code fragmentation
- jdocs documentation, not perfect, but it's a start! :)
- code that run on the server and the client = less maintenance

:sweat_smile:

**Pull request merged**
