### PR TITLE
hash and query data is now also part of an route event

### PR DESCRIPTION
**Pull request by ottiker**
Routes can now contain url query and hash data.

``` js
self.route('/my/url?arg1=value#hash');
```

### CODE REVIEW

**Comment by ottiker** [comment]
Note to update the applications route listener regex.

**Comment by ottiker** [comment]
Append this to your route regex, to make it compatible with url parameters:
`/my/route/?((?=\\?|#).*|(?!.))$`

**Comment by IonicaBizau** [comment]
After this will be merged, we have to emit routes with ending slash. The ending slash is not appended anymore.

**Comment by ottiker** [comment]
If we have `/?` in the regex listeners, than it's optional to have a slash at the end of a route. Every project should choose the convention they like; with or without slash at the end.

**Comment by IonicaBizau** [comment]
@adioo Yeps, but not when we are catching dynamic routes:

``` js
{
  ...,
  "item": {
    "path": "/foo/{bar}/"
  }
}
```

**Comment by ottiker** [comment]
This pull request will fix issue #37 and issue #29

**Comment by ottiker** [comment]
The improved "item" config also fixes issue #18.

**Pull request merged**
